// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	database "github.com/go-park-mail-ru/2019_1_Escapade/internal/pkg/database"
	mock "github.com/stretchr/testify/mock"

	models "github.com/go-park-mail-ru/2019_1_Escapade/internal/pkg/models"
)

// RecordRepositoryI is an autogenerated mock type for the RecordRepositoryI type
type RecordRepositoryI struct {
	mock.Mock
}

// Create provides a mock function with given fields: tx, id
func (_m *RecordRepositoryI) Create(tx database.TransactionI, id int) error {
	ret := _m.Called(tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(database.TransactionI, int) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: tx, id, record
func (_m *RecordRepositoryI) Update(tx database.TransactionI, id int32, record *models.Record) error {
	ret := _m.Called(tx, id, record)

	var r0 error
	if rf, ok := ret.Get(0).(func(database.TransactionI, int32, *models.Record) error); ok {
		r0 = rf(tx, id, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
