# base image
FROM progrium/consul

# # set consul version
# ENV CONSUL_VERSION 1.2.1

# # create a new directory
# RUN mkdir /consul
# RUN mkdir /consul/config

# # add the config file
# COPY . /consul/config