global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'escapade'
    static_configs:
      - targets: ['api:3001', 'game:3002']
  
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'system'
  #   static_configs:
  #     - targets: ['nodeexporter:9000']
