basePath: /auth
definitions:
  models.ErrorDescription:
    properties:
      error:
        example: unsupported_grant_type
        type: string
      error_description:
        example: The authorization grant type is not supported by the authorization
          server
        type: string
    type: object
  models.SessionToken:
    properties:
      access_token:
        example: "123123123"
        type: string
      expires_in:
        example: 86400
        type: integer
      refresh_token:
        example: "321321321"
        type: string
      token_type:
        example: bearer
        type: string
    type: object
host: localhost:3003
info:
  contact: {}
  description: We don't have a public API, so instead of a real host(explosion.team)
    we specify localhost:3003. To test the following methods, git clone https://github.com/go-park-mail-ru/2019_1_Escapade,
    enter the root directory and run 'docker-compose up -d'
  license: {}
  title: Escapade Explosion AUTH
  version: "1.0"
paths:
  /token:
    post:
      consumes:
      - application/json
      description: Get session token for current client
      operationId: tokenHandler
      parameters:
      - default: '"password"'
        description: '''password'' or ''refresh_token'''
        in: body
        name: grant_type
        required: true
        schema:
          type: string
      - default: '"1"'
        description: client id
        in: body
        name: client_id
        required: true
        schema:
          type: string
      - default: '"1"'
        description: client secret
        in: body
        name: client_secret
        required: true
        schema:
          type: string
      - default: '"username"'
        description: username
        in: body
        name: username
        schema:
          type: string
      - default: '"password"'
        description: password
        in: body
        name: password
        schema:
          type: string
      - default: '"1"'
        description: client id
        in: body
        name: refresh_token
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: token was given
          schema:
            $ref: '#/definitions/models.SessionToken'
        "401":
          description: 'invalid body parameters '
          schema:
            $ref: '#/definitions/models.ErrorDescription'
      summary: Get token
swagger: "2.0"
