version: '3'
services:

  pg:
    image: smartphonejava/api:latest
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/postgresql/main/

  pg-ery:
    image: smartphonejava/pg-ery:latest    
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/postgresql/ery/  

  consul:
    image: smartphonejava/consul:latest
    build:
      context: ./../../../../extra/consul
      dockerfile: Dockerfile

  front:
    image: smartphonejava/front:latest
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/front
